import type { LucideIcon } from "lucide-react";
import {
  Utensils,
  ChefHat,
  Train,
  Bot,
  Droplets,
  Package,
  Home,
  Plane,
  Dumbbell,
  Sparkles,
  Wine,
  ShoppingBag,
  Pill,
  Coffee,
  BookOpen,
  Wifi,
  Camera,
  Music,
  Shirt,
  Car,
  Bike,
  Globe,
  Gamepad2,
  Stethoscope,
  HeartPulse,
  GlassWater,
  ShoppingCart,
  Briefcase,
  Zap,
  CircleDollarSign,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "Dining Out": Utensils,
  "Home Cooking": ChefHat,
  Groceries: ShoppingCart,
  Transport: Train,
  "AI/SaaS": Bot,
  "Sauna/Spa": Droplets,
  Other: Package,
  Rent: Home,
  Travel: Plane,
  Sports: Dumbbell,
  Beauty: Sparkles,
  Drinks: Wine,
  Shopping: ShoppingBag,
  Medical: Stethoscope,
  Health: HeartPulse,
  Medicine: Pill,
  Cafe: Coffee,
  Books: BookOpen,
  Games: Gamepad2,
  Phone: Wifi,
  Camera: Camera,
  Music: Music,
  Clothing: Shirt,
  Car: Car,
  Bicycle: Bike,
  Overseas: Globe,
  Water: GlassWater,
  Work: Briefcase,
  Electricity: Zap,
  Savings: CircleDollarSign,
};

export function getCategoryIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Package;
}
