import type { LucideIcon } from "lucide-react";
import {
  Utensils,
  ChefHat,
  Train,
  Bot,
  Droplets,
  Package,
  Home,
  Plane,
  Dumbbell,
  Sparkles,
  Wine,
  ShoppingBag,
  Pill,
  Coffee,
  BookOpen,
  Wifi,
  Camera,
  Music,
  Shirt,
  Car,
  Bike,
  Globe,
  Gamepad2,
  Stethoscope,
  HeartPulse,
  GlassWater,
  ShoppingCart,
  Briefcase,
  Zap,
  CircleDollarSign,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "外食": Utensils,
  "自炊": ChefHat,
  "食料品": ShoppingCart,
  "交通費": Train,
  "AI/SaaS": Bot,
  "サウナ/スパ": Droplets,
  "その他": Package,
  "家賃": Home,
  "旅行": Plane,
  "スポーツ": Dumbbell,
  "美容": Sparkles,
  "飲み会": Wine,
  "ショッピング": ShoppingBag,
  "医療": Stethoscope,
  "健康": HeartPulse,
  "薬": Pill,
  "カフェ": Coffee,
  "書籍": BookOpen,
  "ゲーム": Gamepad2,
  "通信": Wifi,
  "カメラ": Camera,
  "音楽": Music,
  "衣類": Shirt,
  "車": Car,
  "自転車": Bike,
  "海外": Globe,
  "水道": GlassWater,
  "仕事": Briefcase,
  "電気": Zap,
  "貯金": CircleDollarSign,
};

export function getCategoryIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Package;
}
